CREATE SEQUENCE S_SUBJECT_ID START WITH 1 INCREMENT BY 1;
CREATE TABLE T_SUBJECTS(
       SUBJECT_ID NUMERIC(10,0),
        SUBJECT_NAME VARCHAR(100),
        SUBJECT_COUNT NUMERIC(10,0),
        SUBJECT_STUD_GROUP_ID NUMERIC(10,0),
        SUBJECT_TEACHER_ID NUMERIC(10,0)
)